name: Create draft release

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'  
  #push:
    #tags:
      #- '*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          #tag_name: ${{ github.ref }}
          tag_name: ${{ github.event.inputs.tags }}
          release_name: hiero-otio${{ github.event.inputs.tags }}
          #release_name: hiero-otio${{ github.ref }}
          body: |
            Changes in this release
            * something
            * something

          draft: true
          prerelease: false

      - name: Create Release Archive for Nukepedia
        uses: thedoctor0/zip-release@master
        with:
           #filename: 'hiero-otio-release${{ github.ref }}.zip'
           filename: 'hiero-otio-release${{ github.event.inputs.tags }}.zip'
           exclusions: '*.git*'

      - name: Upload Release Archive
        uses: ncipollo/release-action@v1
        with:
          #artifacts: "hiero-otio-release${{ github.ref }}.zip"
          artifacts: "hiero-otio-release${{ github.event.inputs.tags }}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
