name: Create draft release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: hiero-otio${{ github.ref }}
          body: |
            Changes in this release
            * something
            * something

          draft: true
          prerelease: false

      - name: Create Release Archive for Nukepedia
        uses: thedoctor0/zip-release@master
        env: 
          TAG_NAME: ${GITHUB_REF/refs\/tags\//}
        with:
           filename: 'hiero-otio${{ env.TAG_NAME }}.zip'
           exclusions: '*.git*'

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${GITHUB_REF/refs\/tags\//}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./hiero-otio${{ tag_name }}.zip
          asset_name: hiero-otio${{ tag_name }}.zip
          asset_content_type: application/zip
